---
- name: Check /etc/shadow.lock exists
  stat:
    path: /etc/shadow.lock
  register: shadow_lock


- name: Remove /etc/shadow.lock if it exists
  file:
    path: /etc/shadow.lock
    state: absent
  when: shadow_lock.stat.exists

- name: User | Create User Group
  group:
    name: "{{ user.group|default(user.name) }}"
    system: "{{ user.system|default(omit) }}"

- name: User | Create User
  user:
    comment: "{{ user.comment|default(omit) }}"
    createhome: "{{ user.createhome|default(omit) }}"
    group: "{{ user.group|default(user.name) }}"
    home: "{{ user.home|default(omit) }}"
    shell: "{{ user.shell|default(omit) }}"
    name: "{{ user.name }}"
    system: "{{ user.system|default(omit) }}"
