---
crio_rhel_repo_base_url: 'https://cbs.centos.org/repos/paas7-crio-114-candidate/x86_64/os/'

crio-packages:
  - 'https://cbs.centos.org/kojifiles/packages/cri-o/1.15.3/1.el7/x86_64/cri-o-1.15.3-1.el7.x86_64.rpm'
  - 'https://cbs.centos.org/kojifiles/packages/cri-tools/1.13.0/1.rhaos4.1.gitc06001f.el7/x86_64/cri-tools-1.13.0-1.rhaos4.1.gitc06001f.el7.x86_64.rpm'
